language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "stable"
  - "iojs"
  - "iojs-v1.0.4"
install: npm install
branches:
  only:
    - master
notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/6f5fbe7d518206b74621"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always